storage: ../../.verdaccio/storage
max_body_size: 200mb
auth:
  htpasswd:
    file: ../../.verdaccio/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@codemation/*":
    access: $all
    publish: $anonymous
    unpublish: $anonymous
  "create-codemation":
    access: $all
    publish: $anonymous
    unpublish: $anonymous
  "**":
    access: $all
    publish: $anonymous
    proxy: npmjs
middlewares:
  audit:
    enabled: false
log:
  type: stdout
  format: pretty
  level: http
