// Generated by Codemation CLI. Do not edit manually.
import { Outlet, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/workflows")({
  component: WorkflowsLayoutRouteComponent,
});

function WorkflowsLayoutRouteComponent() {
  return <Outlet />;
}
