// Generated by Codemation CLI. Do not edit manually.
import { WorkflowsScreen } from "@codemation/frontend/client";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

const loadWorkflowSummaries = createServerFn({ method: "GET" }).handler(async () => {
  const [{ WorkflowLoader }, { codemationHost }] = await Promise.all([
    import("@codemation/frontend/server"),
    import("../../codemation.config"),
  ]);
  return await WorkflowLoader.loadSummaries(codemationHost);
});

export const Route = createFileRoute("/workflows/")({
  loader: async () => await loadWorkflowSummaries(),
  component: WorkflowsIndexRouteComponent,
});

function WorkflowsIndexRouteComponent() {
  return <WorkflowsScreen initialWorkflows={Route.useLoaderData()} />;
}
