/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as codemationIndexRouteImport } from './routes/(codemation)/index'
import { Route as codemationWorkflowsRouteImport } from './routes/(codemation)/workflows'
import { Route as codemationWorkflowsIndexRouteImport } from './routes/(codemation)/workflows.index'
import { Route as codemationWorkflowsWorkflowIdRouteImport } from './routes/(codemation)/workflows.$workflowId'
import { Route as codemationApiSplatRouteImport } from './routes/(codemation)/api.$'

const codemationIndexRoute = codemationIndexRouteImport.update({
  id: '/(codemation)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const codemationWorkflowsRoute = codemationWorkflowsRouteImport.update({
  id: '/(codemation)/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const codemationWorkflowsIndexRoute =
  codemationWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => codemationWorkflowsRoute,
  } as any)
const codemationWorkflowsWorkflowIdRoute =
  codemationWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => codemationWorkflowsRoute,
  } as any)
const codemationApiSplatRoute = codemationApiSplatRouteImport.update({
  id: '/(codemation)/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/workflows': typeof codemationWorkflowsRouteWithChildren
  '/': typeof codemationIndexRoute
  '/api/$': typeof codemationApiSplatRoute
  '/workflows/$workflowId': typeof codemationWorkflowsWorkflowIdRoute
  '/workflows/': typeof codemationWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof codemationIndexRoute
  '/api/$': typeof codemationApiSplatRoute
  '/workflows/$workflowId': typeof codemationWorkflowsWorkflowIdRoute
  '/workflows': typeof codemationWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(codemation)/workflows': typeof codemationWorkflowsRouteWithChildren
  '/(codemation)/': typeof codemationIndexRoute
  '/(codemation)/api/$': typeof codemationApiSplatRoute
  '/(codemation)/workflows/$workflowId': typeof codemationWorkflowsWorkflowIdRoute
  '/(codemation)/workflows/': typeof codemationWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/workflows'
    | '/'
    | '/api/$'
    | '/workflows/$workflowId'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/workflows/$workflowId' | '/workflows'
  id:
    | '__root__'
    | '/(codemation)/workflows'
    | '/(codemation)/'
    | '/(codemation)/api/$'
    | '/(codemation)/workflows/$workflowId'
    | '/(codemation)/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  codemationWorkflowsRoute: typeof codemationWorkflowsRouteWithChildren
  codemationIndexRoute: typeof codemationIndexRoute
  codemationApiSplatRoute: typeof codemationApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(codemation)/': {
      id: '/(codemation)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof codemationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(codemation)/workflows': {
      id: '/(codemation)/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof codemationWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(codemation)/workflows/': {
      id: '/(codemation)/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof codemationWorkflowsIndexRouteImport
      parentRoute: typeof codemationWorkflowsRoute
    }
    '/(codemation)/workflows/$workflowId': {
      id: '/(codemation)/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof codemationWorkflowsWorkflowIdRouteImport
      parentRoute: typeof codemationWorkflowsRoute
    }
    '/(codemation)/api/$': {
      id: '/(codemation)/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof codemationApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface codemationWorkflowsRouteChildren {
  codemationWorkflowsWorkflowIdRoute: typeof codemationWorkflowsWorkflowIdRoute
  codemationWorkflowsIndexRoute: typeof codemationWorkflowsIndexRoute
}

const codemationWorkflowsRouteChildren: codemationWorkflowsRouteChildren = {
  codemationWorkflowsWorkflowIdRoute: codemationWorkflowsWorkflowIdRoute,
  codemationWorkflowsIndexRoute: codemationWorkflowsIndexRoute,
}

const codemationWorkflowsRouteWithChildren =
  codemationWorkflowsRoute._addFileChildren(codemationWorkflowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  codemationWorkflowsRoute: codemationWorkflowsRouteWithChildren,
  codemationIndexRoute: codemationIndexRoute,
  codemationApiSplatRoute: codemationApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
