class StartRouteTemplateDefinition {
  constructor(
    public readonly fileName: string,
    public readonly source: string,
  ) {}
}

export class StartRouteTemplateCatalog {
  private static readonly GENERATED_BANNER = "// Generated by Codemation CLI. Do not edit manually.";

  private static readonly GENERATED_ROUTES_DIRECTORY_NAME = "(codemation)";

  private static readonly TEMPLATES = [
    this.createTemplate(
      "index.tsx",
      `
import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/")({
  beforeLoad: () => {
    throw redirect({ to: "/workflows" });
  },
});
`,
    ),
    this.createTemplate(
      "workflows.tsx",
      `
import { Outlet, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/workflows")({
  component: WorkflowsLayoutRouteComponent,
});

function WorkflowsLayoutRouteComponent() {
  return <Outlet />;
}
`,
    ),
    this.createTemplate(
      "workflows.index.tsx",
      `
import { WorkflowsScreen } from "@codemation/frontend/client";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

const loadWorkflowSummaries = createServerFn({ method: "GET" }).handler(async () => {
  const [{ WorkflowLoader }, { codemationHost }] = await Promise.all([
    import("@codemation/frontend/server"),
    import("../../../codemation.config"),
  ]);
  return await WorkflowLoader.loadSummaries(codemationHost);
});

export const Route = createFileRoute("/(codemation)/workflows/")({
  loader: async () => await loadWorkflowSummaries(),
  component: WorkflowsIndexRouteComponent,
});

function WorkflowsIndexRouteComponent() {
  return <WorkflowsScreen initialWorkflows={Route.useLoaderData()} />;
}
`,
    ),
    this.createTemplate(
      "workflows.$workflowId.tsx",
      `
import { WorkflowDetailScreen } from "@codemation/frontend/client";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

const loadWorkflowDetail = createServerFn({ method: "GET" })
  .inputValidator((data: { workflowId: string }) => data)
  .handler(async ({ data }) => {
    const [{ WorkflowLoader }, { codemationHost }] = await Promise.all([
      import("@codemation/frontend/server"),
      import("../../../codemation.config"),
    ]);
    return await WorkflowLoader.loadDetail(codemationHost, data.workflowId);
  });

export const Route = createFileRoute("/(codemation)/workflows/$workflowId")({
  loader: async ({ params }) => await loadWorkflowDetail({ data: { workflowId: params.workflowId } }),
  component: WorkflowDetailRouteComponent,
});

function WorkflowDetailRouteComponent() {
  const initialWorkflow = Route.useLoaderData();
  const { workflowId } = Route.useParams();
  return <WorkflowDetailScreen workflowId={workflowId} initialWorkflow={initialWorkflow} />;
}
`,
    ),
    this.createTemplate(
      "api.$.ts",
      `
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/api/$")({
  server: {
    handlers: {
      GET: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
      POST: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
      PUT: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
      PATCH: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
      DELETE: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
    },
  },
});
`,
    ),
  ] satisfies readonly StartRouteTemplateDefinition[];

  static createApiRoute(): string {
    return this.getTemplate("api.$.ts").source;
  }

  static createIndexRoute(): string {
    return this.getTemplate("index.tsx").source;
  }

  static createWorkflowDetailRoute(): string {
    return this.getTemplate("workflows.$workflowId.tsx").source;
  }

  static createWorkflowsIndexRoute(): string {
    return this.getTemplate("workflows.index.tsx").source;
  }

  static createWorkflowsLayoutRoute(): string {
    return this.getTemplate("workflows.tsx").source;
  }

  static getGeneratedRoutesDirectoryName(): string {
    return this.GENERATED_ROUTES_DIRECTORY_NAME;
  }

  static getLegacyRootRouteFileNames(): readonly string[] {
    return this.TEMPLATES.map((template) => template.fileName);
  }

  static getTemplates(): readonly StartRouteTemplateDefinition[] {
    return this.TEMPLATES;
  }

  static isGeneratedRouteContent(content: string): boolean {
    return content.startsWith(`${this.GENERATED_BANNER}\n`);
  }

  private static createTemplate(fileName: string, sourceBody: string): StartRouteTemplateDefinition {
    return new StartRouteTemplateDefinition(
      fileName,
      `${this.GENERATED_BANNER}\n${sourceBody.trim()}\n`,
    );
  }

  private static getTemplate(fileName: string): StartRouteTemplateDefinition {
    const template = this.TEMPLATES.find((candidate) => candidate.fileName === fileName);
    if (!template) {
      throw new Error(`Unknown start route template: ${fileName}`);
    }
    return template;
  }
}
