export class StartRouteTemplateCatalog {
  static createIndexRoute(): string {
    return `// Generated by Codemation CLI. Do not edit manually.
import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  beforeLoad: () => {
    throw redirect({ to: "/workflows" });
  },
});
`;
  }

  static createWorkflowsLayoutRoute(): string {
    return `// Generated by Codemation CLI. Do not edit manually.
import { Outlet, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/workflows")({
  component: WorkflowsLayoutRouteComponent,
});

function WorkflowsLayoutRouteComponent() {
  return <Outlet />;
}
`;
  }

  static createWorkflowsIndexRoute(): string {
    return `// Generated by Codemation CLI. Do not edit manually.
import { WorkflowsScreen } from "@codemation/frontend/client";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

const loadWorkflowSummaries = createServerFn({ method: "GET" }).handler(async () => {
  const [{ WorkflowLoader }, { codemationHost }] = await Promise.all([
    import("@codemation/frontend/server"),
    import("../../codemation.config"),
  ]);
  return await WorkflowLoader.loadSummaries(codemationHost);
});

export const Route = createFileRoute("/workflows/")({
  loader: async () => await loadWorkflowSummaries(),
  component: WorkflowsIndexRouteComponent,
});

function WorkflowsIndexRouteComponent() {
  return <WorkflowsScreen initialWorkflows={Route.useLoaderData()} />;
}
`;
  }

  static createWorkflowDetailRoute(): string {
    return `// Generated by Codemation CLI. Do not edit manually.
import { WorkflowDetailScreen } from "@codemation/frontend/client";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

const loadWorkflowDetail = createServerFn({ method: "GET" })
  .inputValidator((data: { workflowId: string }) => data)
  .handler(async ({ data }) => {
    const [{ WorkflowLoader }, { codemationHost }] = await Promise.all([
      import("@codemation/frontend/server"),
      import("../../codemation.config"),
    ]);
    return await WorkflowLoader.loadDetail(codemationHost, data.workflowId);
  });

export const Route = createFileRoute("/workflows/$workflowId")({
  loader: async ({ params }) => await loadWorkflowDetail({ data: { workflowId: params.workflowId } }),
  component: WorkflowDetailRouteComponent,
});

function WorkflowDetailRouteComponent() {
  const initialWorkflow = Route.useLoaderData();
  const { workflowId } = Route.useParams();
  return <WorkflowDetailScreen workflowId={workflowId} initialWorkflow={initialWorkflow} />;
}
`;
  }

  static createApiRoute(): string {
    return `// Generated by Codemation CLI. Do not edit manually.
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/api/$")({
  server: {
    handlers: {
      GET: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
      POST: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
    },
  },
});
`;
  }
}
