// Generated by Codemation CLI. Do not edit manually.
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/api/$")({
  server: {
    handlers: {
      GET: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
      POST: async ({ params, request }) => {
        const [{ ApiDispatcher }, { codemationHost }] = await Promise.all([
          import("@codemation/frontend/server"),
          import("../../../codemation.config"),
        ]);
        return await new ApiDispatcher(codemationHost).dispatch(request, params._splat);
      },
    },
  },
});
