// Generated by @codemation/start-plugin. Do not edit manually.

import { CodemationServerGateway } from "@codemation/frontend/server";
import { createFileRoute } from "@tanstack/react-router";
import { codemationConfig } from "virtual:codemation/config";

const serverGateway = new CodemationServerGateway(codemationConfig, "/home/cblokland/projects/made/codemation/apps/test-dev", "/home/cblokland/projects/made/codemation/apps/test-dev/codemation.config.ts");

export const Route = createFileRoute("/(codemation)/api/$")({
  server: {
    handlers: {
      GET: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      POST: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      PUT: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      PATCH: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      DELETE: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
    },
  },
});
