// Generated by Codemation CLI. Do not edit manually.
import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/")({
  beforeLoad: () => {
    throw redirect({ to: "/workflows" });
  },
});
