// Generated by @codemation/start-plugin. Do not edit manually.

import { Outlet, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/workflows")({
  component: WorkflowsLayoutRouteComponent,
});

function WorkflowsLayoutRouteComponent() {
  return <Outlet />;
}
