// Generated by @codemation/start-plugin. Do not edit manually.

import { WorkflowDetailScreen } from "@codemation/frontend/client";
import { CodemationServerGateway } from "@codemation/frontend/server";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { codemationConfig } from "virtual:codemation/config";

const serverGateway = new CodemationServerGateway(codemationConfig, "/home/cblokland/projects/made/codemation/apps/test-dev", "/home/cblokland/projects/made/codemation/apps/test-dev/codemation.config.ts");

const loadWorkflowDetail = createServerFn({ method: "GET" })
  .inputValidator((data: { workflowId: string }) => data)
  .handler(async ({ data }) => {
    return await serverGateway.loadWorkflowDetail(data.workflowId);
  });

export const Route = createFileRoute("/(codemation)/workflows/$workflowId")({
  loader: async ({ params }) => await loadWorkflowDetail({ data: { workflowId: params.workflowId } }),
  component: WorkflowDetailRouteComponent,
});

function WorkflowDetailRouteComponent() {
  const initialWorkflow = Route.useLoaderData();
  const { workflowId } = Route.useParams();
  return <WorkflowDetailScreen workflowId={workflowId} initialWorkflow={initialWorkflow} />;
}
