// Generated by @codemation/start-plugin. Do not edit manually.

import { WorkflowsScreen } from "@codemation/frontend/client";
import { CodemationServerGateway } from "@codemation/frontend/server";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { codemationConfig } from "virtual:codemation/config";

const serverGateway = new CodemationServerGateway(codemationConfig, "/home/cblokland/projects/made/codemation/apps/test-dev", "/home/cblokland/projects/made/codemation/apps/test-dev/codemation.config.ts");

const loadWorkflowSummaries = createServerFn({ method: "GET" }).handler(async () => {
  return await serverGateway.loadWorkflowSummaries();
});

export const Route = createFileRoute("/(codemation)/workflows/")({
  loader: async () => await loadWorkflowSummaries(),
  component: WorkflowsIndexRouteComponent,
});

function WorkflowsIndexRouteComponent() {
  return <WorkflowsScreen initialWorkflows={Route.useLoaderData()} />;
}
