// Generated by Codemation CLI. Do not edit manually.
import { WorkflowDetailScreen } from "@codemation/frontend/client";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";

const loadWorkflowDetail = createServerFn({ method: "GET" })
  .inputValidator((data: { workflowId: string }) => data)
  .handler(async ({ data }) => {
    const [{ WorkflowLoader }, { codemationHost }] = await Promise.all([
      import("@codemation/frontend/server"),
      import("../../../codemation.config"),
    ]);
    return await WorkflowLoader.loadDetail(codemationHost, data.workflowId);
  });

export const Route = createFileRoute("/(codemation)/workflows/$workflowId")({
  loader: async ({ params }) => await loadWorkflowDetail({ data: { workflowId: params.workflowId } }),
  component: WorkflowDetailRouteComponent,
});

function WorkflowDetailRouteComponent() {
  const initialWorkflow = Route.useLoaderData();
  const { workflowId } = Route.useParams();
  return <WorkflowDetailScreen workflowId={workflowId} initialWorkflow={initialWorkflow} />;
}
