import type { TypeToken } from "./di";
import type {
  ActivationIdFactory,
  BinaryStorage,
  CredentialService,
  ExecutionContextFactory,
  NodeActivationObserver,
  NodeActivationScheduler,
  NodeResolver,
  PersistedWorkflowTokenRegistryLike,
  RunDataFactory,
  RunIdFactory,
  RunStateStore,
  TriggerSetupStateStore,
  WebhookRegistrar,
  WorkflowRegistry,
  WorkflowRunnerResolver,
  WorkflowRunnerService,
} from "./types";
import type { RunEventBus } from "./events/runEvents";

export const CoreTokens = {
  PersistedWorkflowTokenRegistry: Symbol.for("codemation.core.PersistedWorkflowTokenRegistry") as TypeToken<PersistedWorkflowTokenRegistryLike>,
  CredentialService: Symbol.for("codemation.core.CredentialService") as TypeToken<CredentialService>,
  WorkflowRunnerService: Symbol.for("codemation.core.WorkflowRunnerService") as TypeToken<WorkflowRunnerService>,
  WorkflowRunnerResolver: Symbol.for("codemation.core.WorkflowRunnerResolver") as TypeToken<WorkflowRunnerResolver>,
  WorkflowRegistry: Symbol.for("codemation.core.WorkflowRegistry") as TypeToken<WorkflowRegistry>,
  ServiceContainer: Symbol.for("codemation.core.ServiceContainer") as TypeToken<import("./di").Container>,
  NodeResolver: Symbol.for("codemation.core.NodeResolver") as TypeToken<NodeResolver>,
  WebhookRegistrar: Symbol.for("codemation.core.WebhookRegistrar") as TypeToken<WebhookRegistrar>,
  NodeActivationObserver: Symbol.for("codemation.core.NodeActivationObserver") as TypeToken<NodeActivationObserver>,
  RunIdFactory: Symbol.for("codemation.core.RunIdFactory") as TypeToken<RunIdFactory>,
  ActivationIdFactory: Symbol.for("codemation.core.ActivationIdFactory") as TypeToken<ActivationIdFactory>,
  RunStateStore: Symbol.for("codemation.core.RunStateStore") as TypeToken<RunStateStore>,
  TriggerSetupStateStore: Symbol.for("codemation.core.TriggerSetupStateStore") as TypeToken<TriggerSetupStateStore>,
  NodeActivationScheduler: Symbol.for("codemation.core.NodeActivationScheduler") as TypeToken<NodeActivationScheduler>,
  RunDataFactory: Symbol.for("codemation.core.RunDataFactory") as TypeToken<RunDataFactory>,
  ExecutionContextFactory: Symbol.for("codemation.core.ExecutionContextFactory") as TypeToken<ExecutionContextFactory>,
  RunEventBus: Symbol.for("codemation.core.RunEventBus") as TypeToken<RunEventBus>,
  BinaryStorage: Symbol.for("codemation.core.BinaryStorage") as TypeToken<BinaryStorage>,
  WebhookBasePath: Symbol.for("codemation.core.WebhookBasePath") as TypeToken<string>,
} as const;
