import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export class CodemationRouteGenerator {
  constructor(
    private readonly routesDirectory: string,
    private readonly configPath: string,
  ) {}

  async sync(): Promise<void> {
    const codemationDir = path.resolve(this.routesDirectory, "(codemation)");
    await mkdir(codemationDir, { recursive: true });

    for (const [fileName, content] of Object.entries(this.createRouteTemplates())) {
      const filePath = path.resolve(codemationDir, fileName);
      const banner = "// Generated by @codemation/start-plugin. Do not edit manually.\n\n";
      await writeFile(filePath, banner + content.trim() + "\n", "utf8");
    }
  }

  private createRouteTemplates(): Readonly<Record<string, string>> {
    const consumerRoot = JSON.stringify(path.dirname(this.configPath));
    const configPath = JSON.stringify(this.configPath);
    return {
      "index.tsx": `import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/")({
  beforeLoad: () => {
    throw redirect({ to: "/workflows" });
  },
});
`,
      "workflows.tsx": `import { Outlet, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/(codemation)/workflows")({
  component: WorkflowsLayoutRouteComponent,
});

function WorkflowsLayoutRouteComponent() {
  return <Outlet />;
}
`,
      "workflows.index.tsx": `import { WorkflowsScreen } from "@codemation/frontend/client";
import { CodemationServerGateway } from "@codemation/frontend/server";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { codemationConfig } from "virtual:codemation/config";

const serverGateway = new CodemationServerGateway(codemationConfig, ${consumerRoot}, ${configPath});

const loadWorkflowSummaries = createServerFn({ method: "GET" }).handler(async () => {
  return await serverGateway.loadWorkflowSummaries();
});

export const Route = createFileRoute("/(codemation)/workflows/")({
  loader: async () => await loadWorkflowSummaries(),
  component: WorkflowsIndexRouteComponent,
});

function WorkflowsIndexRouteComponent() {
  return <WorkflowsScreen initialWorkflows={Route.useLoaderData()} />;
}
`,
      "workflows.$workflowId.tsx": `import { WorkflowDetailScreen } from "@codemation/frontend/client";
import { CodemationServerGateway } from "@codemation/frontend/server";
import { createFileRoute } from "@tanstack/react-router";
import { createServerFn } from "@tanstack/react-start";
import { codemationConfig } from "virtual:codemation/config";

const serverGateway = new CodemationServerGateway(codemationConfig, ${consumerRoot}, ${configPath});

const loadWorkflowDetail = createServerFn({ method: "GET" })
  .inputValidator((data: { workflowId: string }) => data)
  .handler(async ({ data }) => {
    return await serverGateway.loadWorkflowDetail(data.workflowId);
  });

export const Route = createFileRoute("/(codemation)/workflows/$workflowId")({
  loader: async ({ params }) => await loadWorkflowDetail({ data: { workflowId: params.workflowId } }),
  component: WorkflowDetailRouteComponent,
});

function WorkflowDetailRouteComponent() {
  const initialWorkflow = Route.useLoaderData();
  const { workflowId } = Route.useParams();
  return <WorkflowDetailScreen workflowId={workflowId} initialWorkflow={initialWorkflow} />;
}
`,
      "api.$.ts": `import { CodemationServerGateway } from "@codemation/frontend/server";
import { createFileRoute } from "@tanstack/react-router";
import { codemationConfig } from "virtual:codemation/config";

const serverGateway = new CodemationServerGateway(codemationConfig, ${consumerRoot}, ${configPath});

export const Route = createFileRoute("/(codemation)/api/$")({
  server: {
    handlers: {
      GET: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      POST: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      PUT: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      PATCH: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
      DELETE: async ({ params, request }) => await serverGateway.dispatch(request, params._splat),
    },
  },
});
`,
    } as const;
  }
}
